### ISSUE TITLE
Modificar la web para que el agregado de más cursos escale

### ISSUE THREAD

**Issue by lauracion** [MetaDocencia/SitioWeb#11]
Pensar una forma de que al agregar nuevos cursos sea fácil de ubicar los materiales de cada curso

**Comment by paocorrales** [comment]
Tenemos la sección cursos que lleva a una sub página donde están linkeados los distintos cursos. Cada curso luego en otra página (otro .Rmd) con toda la información. 

@lauracion te imaginás algo distinto? 

Se que el tema que estamos usando tiene algo resuelto para cursos pero seguro es más complejo que un simple .Rmd con toda la información.

**Comment by lauracion** [comment]
No pense nada. Creo que un curso abajo del otro no es lo ideal y este issue surgio por eso. No tengo sugerencias especificas. Idealmente habria que hacer una lluvia de ideas para ver si lo continuamos asi o lo reformateamos.

**Comment by yabellini** [comment]
El tema que usamos permite generar como subsitios para cada curso, dentro de ese mini-subsitio uno puede darle la estructura que quiera.  En mi página hay ejemplos: https://yabellini.netlify.app/courses/

También podemos hacer que los cursos aparezcan en la pagina principal y luego vaya a esos mini-subsitios como esto que hice acá: https://learning-learnr.netlify.app/

Igual, si aún no tenemos mucha más oferta, podemos agregar los que yo quería agregar (los de INTA y el de learnr) a la estructura actual y luego la cambiamos cuando decidamos como hacerlo.  Asi tenemos esa info en la web, si no, no está y es una pena porque son cosas que hicimos y que hoy no se ven reflejadas en nuestro sitio.

**Comment by lauracion** [comment]
Yo no tengo ancho de banda para ver esto en este momento con el detalle que merece. Lo que decida la mayoria del equipo coordinador sobre este tema va a estar muy bien.

**Comment by paocorrales** [comment]
Agreguemos los cursos como venimos haciendo hasta ahora y luego capaz le
encontramos la vuelta. Es una pena que no estén y no creo que tengamos
tiempo de pensar esto mejor pronto.

**Comment by yabellini** [comment]
Yo ya agregué el de learnr.  Durante estas semanas sigo con los de INTA.

**Comment by paocorrales** [comment]
Le dimos una vueltita de tuerca con @eliocamp 

https://www.metadocencia.org/cursos/

**Comment by paocorrales** [comment]
Con el nuevo layout doy por cerrado el tema. Si alguien tiene una mejor idea se re-abre en el futuro!
