### ISSUE TITLE
Modificación de un link

### ISSUE THREAD

**Issue by marielaraj** [MetaDocencia/SitioWeb#121]
En la página https://www.metadocencia.org/curso/zoom/ , el link "Presentación que usamos en el curso" a las slides no es correcto, manda nuevamente a la página https://www.metadocencia.org/curso/zoom/.

**Comment by aliasLaurel** [comment]
Hola! Lo dejé sin link porque aún no estaban disponibles las diapositivas. ¿Les parece mejor que lo saquemos del todo?

**Comment by melibleq** [comment]
Cerrado por https://github.com/MetaDocencia/SitioWeb/pull/133. Gracias chicas y @4iro!
