### ISSUE TITLE
Cambiar "Metadocentes" por "Equipo Coordinador"

### ISSUE THREAD

**Issue by eliocamp** [MetaDocencia/SitioWeb#13]
Queremos cambiar el título del "core team" en la versión en español para que responda más a la realidad. 

En la versión en español, en cada autor (eliocamp, lacion, npalopoli, paocorrales y yabellini) hay que cambiar 

```
user_groups:
- MetaDocentes
```

por 

```
user_groups:
- Equipo Coordinador
```

Y luego en home/equipo.md hay que cambiar el user_groups para que tenga el nuevo nombre.

**Comment by 4iro** [comment]
Done! Cualquier cosa me avisas. Saludos!

**Comment by eliocamp** [comment]
Gracias!!
