### ISSUE TITLE
Actualización de la web - Limpieza de primavera 2020

### ISSUE THREAD

**Issue by paocorrales** [MetaDocencia/SitioWeb#32]
La web necesita un poquito de amor para dejarla lista para todo lo que vienen en 2021. Acá una lista de algunas cosas que veo y cambiaría:

*Página de inicio*
- [x] En la primera sección: "Cursos cortos para virtualizar tu enseñanza" -->  "Cursos cortos para desarrollar clases activas aplicando herramientas prácticas" o algo así, corriéndonos un poco de lo "virtual"
- [x] En la segunda sección: "Qué ofrecemos" --> de nuevo, corrernos un poquito de las clases virtuales y resaltar más la idea de comunidad.
- [x] Orden de las secciónes: sacaría cursos (ya hay link en la barra superior y en la primera sección), correría la sección equipo hacia el final, ya es muy larga. En resumen: Landing sobre los cursos, sobre metadocencia, publicaciones, prensa, Equipo, Auspiciante (agregamos a CS&S?) y contacto
- [x] Nueva sección en el menú sobre como sumarse al equipo

*Sección cursos* --> Issue #11

**Comment by eliocamp** [comment]
- [ ] Cambiar "Formulario de pre-inscripción" a "Registración" en el Hero
- [ ] Cambiar "pre-inscribite" por "registrate" en la página de cursos. 
- [ ] Sacar el "¿Querés que te mandemos novedades?" en el about.

**Comment by paocorrales** [comment]
Listo!
