### ISSUE TITLE
Post de RStudio en español

### ISSUE THREAD

**Issue by yabellini** [MetaDocencia/SitioWeb#34]
Traducir el post al español y ponerlo en nuestra web.

**Comment by yabellini** [comment]
Ya está la primera versión para revisión de @paocorrales y @PatriLoto

**Comment by paocorrales** [comment]
Revisada! Recién hice un comit con algunos cambios menores. Para mi ya sale con fritas!

**Comment by PatriLoto** [comment]
Hicé un commit con algunas sugerencias de las primeras secciones.  Mañana sigo con la revisión.
