### ISSUE TITLE
facilitar la navegación hacia los cursos activos

### ISSUE THREAD

**Issue by lauracion** [MetaDocencia/SitioWeb#49]
me pregunto si no ayudara poner solos los cursos que estaremos ofreciendo. 
justo el de learnr queda ordenado luego del intro al abc y no esta activo 😢 
en mi experiencia, todo lo que podamos hacer para facilitarle la navegacion a nuetra audiencia nos suma
seria genial que los primeros tres que se muestra en el escroleo de la landing sean los que estan efectivamente activos - asi nadie cree que el de enseñar a programar es el de learnr

**Comment by paocorrales** [comment]
Estamos ofreciendo todos ahora así que ya no cuenta este issue :)
