### ISSUE TITLE
Cambiar descripción en home

### ISSUE THREAD

**Issue by NPalopoli** [MetaDocencia/SitioWeb#58]
Al tope de la home de la web dice "Cursos cortos para enseñar online" y en inglés, "Short courses to teach active classes". 

Propongo cambiar la descripción en español por "Cursos cortos para aprender a enseñar mejor" (o llegar entre todes a una mejor descripción).

**Comment by yabellini** [comment]
Hice el cambio sugerido por Nico porque va en línea con lo que venimos discuento de agregar mas material de presencial e hibrido y reslatar als cosas que sirven más allá de la modalidad.
