### ISSUE TITLE
code of conduct page has no title in the metadata

### ISSUE THREAD

**Issue by maelle** [MetaDocencia/SitioWeb#62]
I.e. there is no frontmatter (YAML or TOML) so there's no title in the site head for that page, nor in the RSS feed (well it's not an interesting page for the RSS feed, I suppose the blog feed is more important, but that's where I saw the warning).

**Comment by eliocamp** [comment]
Woudl adding 

```yaml
---
title: Code of conduct
---
```

solve this?

**Comment by maelle** [comment]
yes I think something like that should work!

**Comment by eliocamp** [comment]
Ok, then it's done! 
Thanks again for the issues and the PR.

**Comment by maelle** [comment]
¡De nada! :-)
