### ISSUE TITLE
Link a Slack roto

### ISSUE THREAD

**Issue by lauracion** [MetaDocencia/SitioWeb#92]
Hay que cambiarlo por este https://join.slack.com/t/metadocencia/shared_invite/zt-1a3cri0ht-_Ws~Eq2VkkQ9L64rvu2czA

Intenté hacerlo [en este commit](https://github.com/MetaDocencia/SitioWeb/compare/012520b4be89...a1f729ec6133) pero no logré cambiarlo

Los links sin fecha de expiración a Slack expiran luego de 100 usos - habrá forma de no tener que estar cambiando la web cuando se usan 100 veces?

**Comment by lauracion** [comment]
Oi, @melibleq! Podrías investigar este issue por favor? Obrigada 🙏

**Comment by melibleq** [comment]
Claro! A ver si encuentro el problema 🔎

**Comment by lauracion** [comment]
Muchas gracias, Melissa! Evitar tener que cambiarlo cada 100 ingresos, sería genial.
Yo no estoy logrando que funcione el link que puse en la web de metadocencia. En nuestra proxima reunion te muestro a qué me refiero :-)

**Comment by lauracion** [comment]
Excelente!! Muchas gracias, Melissa! Buen viernes❣️

**Comment by melibleq** [comment]
Problema solucionado! Todos los links han sido reemplazados por https://w3id.org/metadocencia/slack y cada vez que se cambia el link para unirse a Slack, basta con editarlo en [este archivo](https://github.com/perma-id/w3id.org/blob/master/metadocencia/.htaccess).
